package domen;
// Generated Sep 16, 2014 3:44:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ispit generated by hbm2java
 */
public class Ispit  implements java.io.Serializable {


     private int ispitId;
     private String naziv;
     private Set<Polozenispit> polozenispits = new HashSet<Polozenispit>(0);

    public Ispit() {
    }

	
    public Ispit(int ispitId, String naziv) {
        this.ispitId = ispitId;
        this.naziv = naziv;
    }
    public Ispit(int ispitId, String naziv, Set<Polozenispit> polozenispits) {
       this.ispitId = ispitId;
       this.naziv = naziv;
       this.polozenispits = polozenispits;
    }
   
    public int getIspitId() {
        return this.ispitId;
    }
    
    public void setIspitId(int ispitId) {
        this.ispitId = ispitId;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set<Polozenispit> getPolozenispits() {
        return this.polozenispits;
    }
    
    public void setPolozenispits(Set<Polozenispit> polozenispits) {
        this.polozenispits = polozenispits;
    }




}


