package domen;
// Generated Sep 16, 2014 3:44:36 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Mesto generated by hbm2java
 */
public class Mesto implements java.io.Serializable {

    private int postanskiBroj;
    private String naziv;
    private Set<Student> students = new HashSet<Student>(0);

    public Mesto() {
    }

    public Mesto(int postanskiBroj, String naziv) {
        this.postanskiBroj = postanskiBroj;
        this.naziv = naziv;
    }

    public Mesto(int postanskiBroj, String naziv, Set<Student> students) {
        this.postanskiBroj = postanskiBroj;
        this.naziv = naziv;
        this.students = students;
    }

    public int getPostanskiBroj() {
        return this.postanskiBroj;
    }

    public void setPostanskiBroj(int postanskiBroj) {
        this.postanskiBroj = postanskiBroj;
    }

    public String getNaziv() {
        return this.naziv;
    }

    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    public Set<Student> getStudents() {
        return this.students;
    }

    public void setStudents(Set<Student> students) {
        this.students = students;
    }

    @Override
    public String toString() {
        return naziv;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + this.postanskiBroj;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Mesto other = (Mesto) obj;
        if (this.postanskiBroj != other.postanskiBroj) {
            return false;
        }
        return true;
    }

}
