package domen;
// Generated Sep 16, 2014 3:44:36 PM by Hibernate Tools 3.6.0



/**
 * Polozenispit generated by hbm2java
 */
public class Polozenispit  implements java.io.Serializable {


     private PolozenispitId id;
     private Sluzbenik sluzbenik;
     private Student student;
     private Ispit ispit;
     private int ocena;
     private boolean prijavljen;

    public Polozenispit() {
    }

    public Polozenispit(PolozenispitId id, Sluzbenik sluzbenik, Student student, Ispit ispit, int ocena, boolean prijavljen) {
       this.id = id;
       this.sluzbenik = sluzbenik;
       this.student = student;
       this.ispit = ispit;
       this.ocena = ocena;
       this.prijavljen = prijavljen;
    }
   
    public PolozenispitId getId() {
        return this.id;
    }
    
    public void setId(PolozenispitId id) {
        this.id = id;
    }
    public Sluzbenik getSluzbenik() {
        return this.sluzbenik;
    }
    
    public void setSluzbenik(Sluzbenik sluzbenik) {
        this.sluzbenik = sluzbenik;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Ispit getIspit() {
        return this.ispit;
    }
    
    public void setIspit(Ispit ispit) {
        this.ispit = ispit;
    }
    public int getOcena() {
        return this.ocena;
    }
    
    public void setOcena(int ocena) {
        this.ocena = ocena;
    }
    public boolean isPrijavljen() {
        return this.prijavljen;
    }
    
    public void setPrijavljen(boolean prijavljen) {
        this.prijavljen = prijavljen;
    }




}


