package domen;
// Generated Sep 16, 2014 3:44:36 PM by Hibernate Tools 3.6.0



/**
 * PolozenispitId generated by hbm2java
 */
public class PolozenispitId  implements java.io.Serializable {


     private int ispit;
     private String student;
     private String sluzbenik;

    public PolozenispitId() {
    }

    public PolozenispitId(int ispit, String student, String sluzbenik) {
       this.ispit = ispit;
       this.student = student;
       this.sluzbenik = sluzbenik;
    }
   
    public int getIspit() {
        return this.ispit;
    }
    
    public void setIspit(int ispit) {
        this.ispit = ispit;
    }
    public String getStudent() {
        return this.student;
    }
    
    public void setStudent(String student) {
        this.student = student;
    }
    public String getSluzbenik() {
        return this.sluzbenik;
    }
    
    public void setSluzbenik(String sluzbenik) {
        this.sluzbenik = sluzbenik;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PolozenispitId) ) return false;
		 PolozenispitId castOther = ( PolozenispitId ) other; 
         
		 return (this.getIspit()==castOther.getIspit())
 && ( (this.getStudent()==castOther.getStudent()) || ( this.getStudent()!=null && castOther.getStudent()!=null && this.getStudent().equals(castOther.getStudent()) ) )
 && ( (this.getSluzbenik()==castOther.getSluzbenik()) || ( this.getSluzbenik()!=null && castOther.getSluzbenik()!=null && this.getSluzbenik().equals(castOther.getSluzbenik()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIspit();
         result = 37 * result + ( getStudent() == null ? 0 : this.getStudent().hashCode() );
         result = 37 * result + ( getSluzbenik() == null ? 0 : this.getSluzbenik().hashCode() );
         return result;
   }   


}


