package domen;
// Generated Sep 16, 2014 3:44:36 PM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Racun generated by hbm2java
 */
public class Racun  implements java.io.Serializable {


     private int racunId;
     private Sluzbenik sluzbenik;
     private Student student;
     private Date datum;
     private double ukupanIznos;
     private List<Stavkaracun> stavkaracuns = new ArrayList<Stavkaracun>();

    public Racun() {
    }

	
    public Racun(int racunId, Sluzbenik sluzbenik, Date datum, double ukupanIznos) {
        this.racunId = racunId;
        this.sluzbenik = sluzbenik;
        this.datum = datum;
        this.ukupanIznos = ukupanIznos;
    }
    public Racun(int racunId, Sluzbenik sluzbenik, Student student, Date datum, double ukupanIznos, List<Stavkaracun> stavkaracuns) {
       this.racunId = racunId;
       this.sluzbenik = sluzbenik;
       this.student = student;
       this.datum = datum;
       this.ukupanIznos = ukupanIznos;
       this.stavkaracuns = stavkaracuns;
    }
   
    public int getRacunId() {
        return this.racunId;
    }
    
    public void setRacunId(int racunId) {
        this.racunId = racunId;
    }
    public Sluzbenik getSluzbenik() {
        return this.sluzbenik;
    }
    
    public void setSluzbenik(Sluzbenik sluzbenik) {
        this.sluzbenik = sluzbenik;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public double getUkupanIznos() {
        return this.ukupanIznos;
    }
    
    public void setUkupanIznos(double ukupanIznos) {
        this.ukupanIznos = ukupanIznos;
    }
    public List<Stavkaracun> getStavkaracuns() {
        return this.stavkaracuns;
    }
    
    public void setStavkaracuns(List<Stavkaracun> stavkaracuns) {
        this.stavkaracuns = stavkaracuns;
    }




}


