package domen;
// Generated Sep 16, 2014 3:44:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Sluzbenik generated by hbm2java
 */
public class Sluzbenik  implements java.io.Serializable {


     private String korisnickoIme;
     private String korisnickaSifra;
     private String ime;
     private String prezime;
     private Set<Polozenispit> polozenispits = new HashSet<Polozenispit>(0);
     private Set<Racun> racuns = new HashSet<Racun>(0);

    public Sluzbenik() {
    }

	
    public Sluzbenik(String korisnickoIme, String korisnickaSifra, String ime, String prezime) {
        this.korisnickoIme = korisnickoIme;
        this.korisnickaSifra = korisnickaSifra;
        this.ime = ime;
        this.prezime = prezime;
    }
    public Sluzbenik(String korisnickoIme, String korisnickaSifra, String ime, String prezime, Set<Polozenispit> polozenispits, Set<Racun> racuns) {
       this.korisnickoIme = korisnickoIme;
       this.korisnickaSifra = korisnickaSifra;
       this.ime = ime;
       this.prezime = prezime;
       this.polozenispits = polozenispits;
       this.racuns = racuns;
    }
   
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }
    public String getKorisnickaSifra() {
        return this.korisnickaSifra;
    }
    
    public void setKorisnickaSifra(String korisnickaSifra) {
        this.korisnickaSifra = korisnickaSifra;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public Set<Polozenispit> getPolozenispits() {
        return this.polozenispits;
    }
    
    public void setPolozenispits(Set<Polozenispit> polozenispits) {
        this.polozenispits = polozenispits;
    }
    public Set<Racun> getRacuns() {
        return this.racuns;
    }
    
    public void setRacuns(Set<Racun> racuns) {
        this.racuns = racuns;
    }




}


