package domen;
// Generated Sep 16, 2014 3:44:36 PM by Hibernate Tools 3.6.0



/**
 * StavkaracunId generated by hbm2java
 */
public class StavkaracunId  implements java.io.Serializable {


     private int stavkaRacunaId;
     private int racun;

    public StavkaracunId() {
    }

    public StavkaracunId(int stavkaRacunaId, int racun) {
       this.stavkaRacunaId = stavkaRacunaId;
       this.racun = racun;
    }
   
    public int getStavkaRacunaId() {
        return this.stavkaRacunaId;
    }
    
    public void setStavkaRacunaId(int stavkaRacunaId) {
        this.stavkaRacunaId = stavkaRacunaId;
    }
    public int getRacun() {
        return this.racun;
    }
    
    public void setRacun(int racun) {
        this.racun = racun;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StavkaracunId) ) return false;
		 StavkaracunId castOther = ( StavkaracunId ) other; 
         
		 return (this.getStavkaRacunaId()==castOther.getStavkaRacunaId())
 && (this.getRacun()==castOther.getRacun());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStavkaRacunaId();
         result = 37 * result + this.getRacun();
         return result;
   }   


}


