package domen;
// Generated Sep 16, 2014 3:44:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String jmbg;
     private Mesto mesto;
     private String ime;
     private String prezime;
     private String brIndeksa;
     private String ulica;
     private String broj;
     private Set<Polozenispit> polozenispits = new HashSet<Polozenispit>(0);
     private Set<Racun> racuns = new HashSet<Racun>(0);

    public Student() {
    }

	
    public Student(String jmbg, Mesto mesto, String ime, String prezime, String brIndeksa, String ulica, String broj) {
        this.jmbg = jmbg;
        this.mesto = mesto;
        this.ime = ime;
        this.prezime = prezime;
        this.brIndeksa = brIndeksa;
        this.ulica = ulica;
        this.broj = broj;
    }
    public Student(String jmbg, Mesto mesto, String ime, String prezime, String brIndeksa, String ulica, String broj, Set<Polozenispit> polozenispits, Set<Racun> racuns) {
       this.jmbg = jmbg;
       this.mesto = mesto;
       this.ime = ime;
       this.prezime = prezime;
       this.brIndeksa = brIndeksa;
       this.ulica = ulica;
       this.broj = broj;
       this.polozenispits = polozenispits;
       this.racuns = racuns;
    }
   
    public String getJmbg() {
        return this.jmbg;
    }
    
    public void setJmbg(String jmbg) {
        this.jmbg = jmbg;
    }
    public Mesto getMesto() {
        return this.mesto;
    }
    
    public void setMesto(Mesto mesto) {
        this.mesto = mesto;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getBrIndeksa() {
        return this.brIndeksa;
    }
    
    public void setBrIndeksa(String brIndeksa) {
        this.brIndeksa = brIndeksa;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public String getBroj() {
        return this.broj;
    }
    
    public void setBroj(String broj) {
        this.broj = broj;
    }
    public Set<Polozenispit> getPolozenispits() {
        return this.polozenispits;
    }
    
    public void setPolozenispits(Set<Polozenispit> polozenispits) {
        this.polozenispits = polozenispits;
    }
    public Set<Racun> getRacuns() {
        return this.racuns;
    }
    
    public void setRacuns(Set<Racun> racuns) {
        this.racuns = racuns;
    }




}


